#!/bin/sh
# vim:ts=2:sw=2:et -*- mode: sh; sh-basic-offset: 2; tab-width: 2; indent-tabs-mode: nil; -*-
set -e

case "$1" in
  install|upgrade)
    usr_share="/usr/share/raspi-boot-alternatives"
    divert_dir="${usr_share}/diversions"
    for diversion in \
      "/etc/kernel/postinst.d/z50-raspi-firmware" \
      "/etc/initramfs/post-update.d/z50-raspi-firmware"
    do
      dst="${divert_dir}${diversion}"
      mkdir -p "$(dirname ${dst})"
      dpkg-divert --package raspi-boot-alternatives --rename \
        --divert "${dst}" \
        --add "${diversion}"
    done
    ;;
esac

exit 0
